Add/query filter
ash-framework/core pull request #7
Opened 2017-01-16 08:32 UTC by markstuart

Hmm... still not sure about this one @digitalsadhu. It's working for most cases, but deeply nested case (last test) fails. I haven't really looked too hard into that one, but I'd like to get your eyes over this before I go any further anyway.

I'm not particularly happy with some of it, and will spend more time getting function naming and responsibilities sorted a bit.

Do you want the QueryFilter to return an sql query string? Or just the knex promise so that other operations can be chained/performed on the knex object?

2017-01-16 09:18 UTC, digitalsadhu reviewed
Looking good. You say some tests won't pass with this approach? What needs to change?

2017-01-16 09:18 UTC, digitalsadhu commented on src/classes/query-builder.js
> +const capitalise = word => {
We should probably use a go to string manipulation lib for things like this

2017-01-16 09:18 UTC, digitalsadhu commented on src/classes/query-builder.js
> +    switch (operator) {
Perhaps a data structure and processing function could work here?

2017-01-16 09:18 UTC, digitalsadhu commented on src/classes/query-builder.js
> +        if (!queryFilter.Model.attributes[key]) return // TODO: throw an error to show that the column name is invalid
This will actually be Model.definition.attributes

2017-01-16 09:18 UTC, digitalsadhu commented on src/classes/query-builder.js
> +  _orBuilder (array) {
I was initially a little unsure about the underscore naming convention but I suppose it's the best option. I guess we probably should make it a convention project wide.

2017-01-16 09:18 UTC, digitalsadhu commented on src/classes/query-builder.js
> +  _addClause (action, args, orWhere) {
Nice.

2017-01-16 09:18 UTC, digitalsadhu commented on src/classes/query-builder.js
> +  _addClause (action, args, orWhere) {
(That you handled and and Or here)

2017-01-16 15:20 UTC, digitalsadhu commented on src/classes/query-builder.js
> +const _ = require('lodash')
```js
const { capitalize } = require('lodash')
```

2017-01-16 15:25 UTC, digitalsadhu commented on src/classes/query-builder.js
> +const _ = require('lodash')
I think destructuring to a function in most cases is the way to go.
With lodash especially this means we could easily refactor to include only parts of lodash or to require modules of lodash via:
```js
const capitalize = require('lodash/capitalize')
```

2017-01-19 05:06 UTC, pnw requested changes
First off, awesome work @markstuart - I think I have some feedback that might help with the issues you mentioned with it breaking on deeply nested stuff.

There's some crazy stuff here with the way you're mutating the state of the QueryFilter class, and I have a gut feeling your nested state management doesn't behave the way you want it to.

In all of your tests, you have the `$or` bit of the filter as the last key that you define. Node I'm pretty sure is consistent in the order it returns Object.keys, such that the order of the keys matter.

```js
> Object.keys({a: 1, b: 2})
['a', 'b']
> Object.keys({b: 2, a: 1})
['b', 'a']
```

I mention this, because you handle nesting within an `$or` filter by mutating the queryBuilder state on the QueryBuilder -- the queryFilter.queryBuilder becomes the inner-nested queryBuilder. 
However, in all of your tests, you define the `$or` segment last in the filters. e.g. `{id: {$gt: 10}, $or: [{title: "hello"}, {title: {$like: "%bye%"}}]}`

10/10 you're missing a test to validate that:

```js
// This filter
const filter = {id: {$gt: 10}, $or: [{title: "hello"}, {title: {$like: "%bye%"}}]}
/*
1. add "id" clause to top level
2. do a bunch of crazy nested stuff + state mutations to handle the "or" clause - set this.queryBuilder to the nested instance, set this.depth > 0
*/

// should behave the same as this filter
const filter = {$or: [{title: "hello"}, {title: {$like: "%bye%"}}], id: {$gt: 10}}
/*
1. do a bunch of crazy nested stuff + state mutations to handle the "or" clause - set this.queryBuilder to the nested instance, set this.depth > 0
2. add "id" clause to top level (but this.depth > 0 now)
*/
```

### Summary
1. The order of the filter keys is significant
2. You're doing crazy state mutations on the `or` filter
3. Once you drop down `this.depth ++` I don't think you come back up to the higher depth properly or that you return to the "top level state" correctly
4. You need a test to make sure that the `or` filter doesn't mutate the QueryFilter in a way that you can't return to `this.depth === 0` after performing an `or` filter

Does that make sense?
I'd check it myself, but I'm having problems running the tests for reasons.


### If I'm correct...
If I'm right about this, I suggest making the recursive stuff actually recursive (and passing the relevant queryBuilder + depth around) instead of the complicated state management system you have going on.

2017-01-19 05:06 UTC, pnw commented on src/classes/query-builder.js
> +  constructor (queryBuilder, Model) {
7/10 Naming here is a mess and it makes the source code unnecessarily difficult to follow along with for fresh eyes, not the least because it makes it hard to use search tools on the codebase. This is a small thing, but inconsistencies like this will add up over the framework.

This might be outside of the scope of this PR maybe, but I don't like how the file is "query builder" but the class here is "query filter" (but the query-filter aka query-builder also owns a queryBuilder) and those names are used interchangeably except for when both the query-filter (aka the query-builder) and the queryBuilder (the one that belongs to the query-builder-aka-query-filter) are used in the same scope.

```js
const postsSelect = db.knex('posts')  // this is a queryBuilder
const builder = new QueryBuilder(postsSelect, models.Post)  // this is a queryBuilder
const result = builder.buildFilter(filter)  // Calling "buildFilter" on the QueryFilter returns a knex queryBuilder instance
```

Suggestions:

1. Rename `class QueryFilter` to just `Query` or something immediately distinguishable from the actual queryBuilder (which is the name you're using for the knex instance)
2. Rename the file to be the same as the class
3. Be consistent with the name usage

2017-01-19 05:06 UTC, pnw commented on src/classes/query-builder.js
> +  constructor (queryBuilder, Model) {
5/10 Seems like these parameters are redundant - you should be able to get a knew queryBuilder instance just by passing the Model instance, yeah? I think Richie said you're just using loopback models for the moment, but even then you can introspect the table name from the model instance.

```js
// imo this makes more sense and is less error-prone for the end-user
const query = new Query(models.Post)
// than having to pass a query builder and then manually identify the type of model every time
const query = new Query(db.knex('post'), models.Post)
```

## Downsides:
### 1 
You're less flexible in cases where e.g. you have multiple datasources for a single model (and therefore need to specify which datasource you need). I don't think that's a real problem though, since loopback only lets you define a single datasource for each model and that doesn't seem to be a problem for them.

```js
const query1 = new Query(db1.knex('post'), models.Post)
const query2 = new Query(db2.knex('post'), models.Post)
```

### 2
You become tightly coupled to knex. After writing that though, I think this class implementation already is tightly coupled to knex anyways, and you'd want to write a whole different class if you wanted to implement the Query on top of another sql-builder library.

2017-01-19 05:06 UTC, pnw commented on src/classes/query-builder.js
> +  _orBuilder (array) {
Is it better to use underscores or just mark the methods as private?

2017-01-19 05:06 UTC, pnw commented on src/classes/query-builder.js
> +      // default should throw error 'Unknown operator'
Any reason to not add that right now instead of having a TODO?

2017-01-19 10:42 UTC, markstuart commented on src/classes/query-builder.js
> +  _orBuilder (array) {
How do you mark them as private?

2017-01-19 11:17 UTC, pnw commented on src/classes/query-builder.js
> +  _orBuilder (array) {
```js
/**
 * @private
 **/
orBuilder (array) {}
```

Basically how ember does it - it really mostly affects the auto-API documentation, or if you bother to read the comments when reading through the code.

2017-03-06 20:05 UTC, digitalsadhu commented
I have merged this code into master manually. Will close this PR.

2017-03-06 20:05 UTC, closed without merging